### ISSUE TITLE
Encoding error in Python3

### ISSUE THREAD

**Issue by Nekmo** [fritzy/SleekXMPP#192]
# Python 3.2.2

```
[nekmo@nagisa ~/Projects/nekbot]$ python manage.py
INFO     Negotiating TLS
INFO     Using SSL version: 3
WARNING  Could not find pyasn1 module. SSL certificate COULD NOT BE VERIFIED.
INFO     Authentication failed: not-authorized
ERROR    Connection error.
ERROR    encoding or errors without a string argument
Traceback (most recent call last):
  File "/home/nekmo/Projects/nekbot/sleekxmpp/xmlstream/xmlstream.py", line 1420, in _process
    if not self.__read_xml():
  File "/home/nekmo/Projects/nekbot/sleekxmpp/xmlstream/xmlstream.py", line 1488, in __read_xml
    self.__spawn_event(xml)
  File "/home/nekmo/Projects/nekbot/sleekxmpp/xmlstream/xmlstream.py", line 1556, in __spawn_event
    handler.prerun(stanza_copy)
  File "/home/nekmo/Projects/nekbot/sleekxmpp/xmlstream/handler/callback.py", line 64, in prerun
    self.run(payload, True)
  File "/home/nekmo/Projects/nekbot/sleekxmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/home/nekmo/Projects/nekbot/sleekxmpp/features/feature_mechanisms/mechanisms.py", line 215, in _handle_success
    final = self.mech.process(stanza['value'])
  File "/home/nekmo/Projects/nekbot/sleekxmpp/xmlstream/stanzabase.py", line 694, in __getitem__
    return getattr(self, get_method)(**kwargs)
  File "/home/nekmo/Projects/nekbot/sleekxmpp/features/feature_mechanisms/stanza/success.py", line 29, in get_value
    return base64.b64decode(bytes(self.xml.text))
  File "/home/nekmo/Projects/nekbot/sleekxmpp/util/misc_ops.py", line 35, in bytes
    return builtins.bytes(text, encoding='utf-8')
TypeError: encoding or errors without a string argument
INFO     Waiting for </stream:stream> from server
[...]
```
# Python 2.7.2

```
[nekmo@nagisa ~/Projects/nekbot]$ python2 manage.py
INFO     Negotiating TLS                                                                                                                               
INFO     Using SSL version: 3                                                                                                                          
WARNING  Could not find pyasn1 module. SSL certificate COULD NOT BE VERIFIED.                                                                          
INFO     Authentication failed: not-authorized                                                                                                         
INFO     Node set to: bot@nekmo.com/nekbot_nagisa_1343644729
WARNING  Could not find pyasn1 module. SSL certificate expiration COULD NOT BE VERIFIED.
```

In the latter case the authentication is correct.

Branch: Develop

**Comment by legastero** [comment]
Sigh, this is what happens when I work on the same projects in two places and only fix a bug in one.

Thanks!
