### ISSUE TITLE
Invalid interpretation of birthday field

### ISSUE THREAD

**Issue by Nekmo** [fritzy/SleekXMPP#194]
vCard field: `<BDAY>1987-02-01</BDAY>`

XEP-0054 example: `<BDAY>1966-08-06</BDAY>`
http://xmpp.org/extensions/xep-0054.html#usecases

Birthday standar:

```
  <!-- Birthday property. Value must be an ISO 8601 formatted
    date or date/time value. -->
  <!ELEMENT BDAY (#PCDATA)>
```

The field meets the standard. However:

```
ValueError: Not a proper ISO 8601 timestamp: missing timezone (Z or +hh[:mm])!
```

The ISO 8601 not requires timezone. This is normal because it's a birthday :-)

Complete traceback:

```
DEBUG    SEND: <iq to="nekmo@nekmo.org" type="get" id="2f0b818b-be31-455a-9869-2a55f0b899c2-F"><vCard xmlns="vcard-temp" /></iq>
DEBUG    RECV: <iq to="bot@nekmo.com/nekbot_nagisa_1343644729" from="nekmo@nekmo.org" id="2f0b818b-be31-455a-9869-2a55f0b899c2-F" type="result"><vCard xmlns="vcard-temp"><BDAY>1987-02-01</BDAY><PHOTO><TYPE>image/png</TYPE><BINVAL>... base64 data ...</BINVAL></PHOTO><URL>http://nekmo.com</URL><NICKNAME>Nekmo</NICKNAME><EMAIL><HOME /><USERID>contacto [at] nekmo.com</USERID></EMAIL><FN>Nekmo</FN></vCard></iq>
Exception in thread vcard:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/nekmo/Projects/nekbot/nekbot/core/commands.py", line 306, in exec_cmd
    report += traceback.format_exc(with_vars=True)
  File "/home/nekmo/Projects/nekbot/nekbot/thirdparty/tracebackturbo.py", line 334, in format_exc
    return ''.join(format_exception(etype, value, tb, limit, with_vars))
  File "/home/nekmo/Projects/nekbot/nekbot/thirdparty/tracebackturbo.py", line 231, in format_exception
    list = list + format_tb(tb, limit, with_vars)
  File "/home/nekmo/Projects/nekbot/nekbot/thirdparty/tracebackturbo.py", line 161, in format_tb
    return format_list(extract_tb(tb, limit), with_vars)
  File "/home/nekmo/Projects/nekbot/nekbot/thirdparty/tracebackturbo.py", line 116, in format_list
    item += format_vars(sorted(locals))
  File "/home/nekmo/Projects/nekbot/nekbot/thirdparty/tracebackturbo.py", line 61, in format_vars
    vars['%s[%s]' % (key, repr(subkey))] = repr(value[subkey])
  File "/home/nekmo/Projects/nekbot/sleekxmpp/xmlstream/stanzabase.py", line 708, in __getitem__
    return plugin[full_attrib]
  File "/home/nekmo/Projects/nekbot/sleekxmpp/xmlstream/stanzabase.py", line 694, in __getitem__
    return getattr(self, get_method)(**kwargs)
  File "/home/nekmo/Projects/nekbot/sleekxmpp/plugins/xep_0054/stanza.py", line 327, in get_bday
    return xep_0082.parse(self.xml.text)
  File "/home/nekmo/Projects/nekbot/sleekxmpp/plugins/xep_0082.py", line 28, in parse
    return parse_iso(time_str)
  File "/home/nekmo/Projects/nekbot/sleekxmpp/thirdparty/mini_dateutil.py", line 225, in parse_iso
    "missing timezone (Z or +hh[:mm])!")
ValueError: Not a proper ISO 8601 timestamp: missing timezone (Z or +hh[:mm])!
```

**Comment by legastero** [comment]
Good catch!

This was an issue in the dateutil fallback replacement, so it affected anything using the XEP-0082 plugin without the dateutil package installed.
