### ISSUE TITLE
SRV Lookup fails because of Unicode

### ISSUE THREAD

**Issue by labjack** [fritzy/SleekXMPP#25]
When I try to use SRV Lookups on Python 2.6 I get the following error:
    DEBUG    Loaded Plugin (XEP-0004) Data Forms
    DEBUG    Loaded Plugin (XEP-0030) Service Discovery
    DEBUG    Loaded Plugin (XEP-0060) Publish-Subscribe
    DEBUG    Loaded Plugin (XEP-0199) XMPP Ping
    DEBUG    Since no address is supplied, attempting SRV lookup.
    Traceback (most recent call last):
    File "example.py", line 82, in <module>
        if xmpp.connect():
    File "/Users/mikef/source/SleekXMPP/sleekxmpp/**init**.py", line 99, in connect
        answers = dns.resolver.query("_xmpp-client._tcp.%s" % self.server, "SRV")
    File "/Library/Python/2.6/site-packages/dns/resolver.py", line 732, in query
        return get_default_resolver().query(qname, rdtype, rdclass, tcp, source)
    File "/Library/Python/2.6/site-packages/dns/resolver.py", line 617, in query 
        source=source)
    File "/Library/Python/2.6/site-packages/dns/query.py", line 113, in udp
        wire = q.to_wire()
    File "/Library/Python/2.6/site-packages/dns/message.py", line 404, in to_wire
        r.add_question(rrset.name, rrset.rdtype, rrset.rdclass)
    File "/Library/Python/2.6/site-packages/dns/renderer.py", line 152, in add_question
        self.output.write(struct.pack("!HH", rdtype, rdclass))
    TypeError: unsupported operand type(s) for &: 'unicode' and 'long'

---

Encoding the "SRV" string back to ASCII fixes the problem.

Line 99 of __init__.py looks like this:
    answers = dns.resolver.query("_xmpp-client._tcp.%s" % self.server, "SRV")
Change to this:
    answers = dns.resolver.query("_xmpp-client._tcp.%s" % self.server, "SRV".encode('ascii', 'replace'))

EDIT: It looks like Tom Nichols (tomstrummer) came up with a **much** better solution.

http://github.com/tomstrummer/SleekXMPP/commit/de4d611d3053f2c4fb5029ba5214996cf3821e02

**Comment by fritzy** [comment]
fixed
