### ISSUE TITLE
1.2.0 fails tests

### ISSUE THREAD

**Issue by Nikoli** [fritzy/SleekXMPP#281]
```
/usr/bin/python3.3 setup.py test
running test
Traceback (most recent call last):
  File "setup.py", line 151, in <module>
    cmdclass     = {'test': TestCommand}
  File "/usr/lib64/python3.3/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.3/distutils/dist.py", line 929, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.3/distutils/dist.py", line 948, in run_command
    cmd_obj.run()
  File "/var/package-manager/tmp/portage/dev-python/sleekxmpp-1.2.0/work/sleekxmpp-1.2.0/testall.py", line 59, in run
    result = run_tests()
  File "/var/package-manager/tmp/portage/dev-python/sleekxmpp-1.2.0/work/sleekxmpp-1.2.0/testall.py", line 32, in run_tests
    __import__(file)
  File "/var/package-manager/tmp/portage/dev-python/sleekxmpp-1.2.0/work/sleekxmpp-1.2.0/tests/test_stream_xep_0325.py", line 19, in <module>
    from sleekxmpp.plugins.xep_0325.device import Device
ImportError: No module named 'sleekxmpp.plugins.xep_0325'
```

```
/usr/bin/python2.7 setup.py test
running test
Traceback (most recent call last):
  File "setup.py", line 151, in <module>
    cmdclass     = {'test': TestCommand}
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/var/package-manager/tmp/portage/dev-python/sleekxmpp-1.2.0/work/sleekxmpp-1.2.0/testall.py", line 59, in run
    result = run_tests()
  File "/var/package-manager/tmp/portage/dev-python/sleekxmpp-1.2.0/work/sleekxmpp-1.2.0/testall.py", line 32, in run_tests
    __import__(file)
  File "/var/package-manager/tmp/portage/dev-python/sleekxmpp-1.2.0/work/sleekxmpp-1.2.0/tests/test_stream_xep_0325.py", line 19, in <module>
    from sleekxmpp.plugins.xep_0325.device import Device
ImportError: No module named xep_0325.device

```

**Comment by legastero** [comment]
Thanks! Should be fixed now.
