### ISSUE TITLE
XEP-0065 Python 3 Unicode Error

### ISSUE THREAD

**Issue by keith-gray-powereng** [fritzy/SleekXMPP#296]
I am trying to transfer a file from sleekxmpp to Pidgin with XEP-0065. I am getting the following error when calling the handshake method:

```
Traceback (most recent call last):
  File "C:\Anaconda\envs\xmpp-bot\lib\site-packages\sleekxmpp\xmlstream\xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "xmpp_bot\xmpp_bot.py", line 62, in message
    sid=sid
  File "C:\Anaconda\envs\xmpp-bot\lib\site-packages\sleekxmpp\plugins\xep_0065\proxy.py", line 87, in handshake
    peer=to)
  File "C:\Anaconda\envs\xmpp-bot\lib\site-packages\sleekxmpp\plugins\xep_0065\proxy.py", line 243, in _connect_proxy
    digest.update(sid)
```

I am creating the sid with the following code:

``` python
sid = str(uuid.uuid4())
```

Can anyone else confirm this is a bug and not user error?

Python version = 3.4.1
sleekxmpp version = 1.3.1 installed via pip and pypi

**Comment by bear** [comment]
referenced PR merged, marking as closed - thanks!
