### ISSUE TITLE
Random crash on Disco Info parsing

### ISSUE THREAD

**Issue by xunien** [fritzy/SleekXMPP#302]
git version: d790465d6d9ecc053349936bf09546eb72906d8d

Hi,
My client is poezio with uses Sleek and sometimes Sleek crash.
Here it is an extract from logs:

```
2014-07-10 10:15:09,493 ERROR:xmlstream:Error processing stream handler: Disco Info
Traceback (most recent call last):
  File "/home/blabla/.local/bin/poezio/src/sleekxmpp/xmlstream/xmlstream.py", line 1669, in _event_runner
    handler.run(args[0])
  File "/home/blabla/.local/bin/poezio/src/sleekxmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/home/blabla/.local/bin/poezio/src/sleekxmpp/plugins/xep_0030/disco.py", line 636, in _handle_disco_info
    iq)
  File "/home/blabla/.local/bin/poezio/src/sleekxmpp/api.py", line 35, in partial
    return self.api.run(self.name, attr, jid, node, ifrom, args)
  File "/home/blabla/.local/bin/poezio/src/sleekxmpp/api.py", line 133, in run
    return handler(jid, node, ifrom, args)
  File "/home/blabla/.local/bin/poezio/src/sleekxmpp/plugins/xep_0030/static.py", line 207, in get_info
    raise XMPPError(condition='item-not-found')
sleekxmpp.exceptions.XMPPError
```

**Comment by cmoreira-daitan** [comment]
Same here. This issue has been closed. Any news about it?
