### ISSUE TITLE
ValueError: unknown event b'end' (PyPy 3.2)

### ISSUE THREAD

**Issue by mdevaev** [fritzy/SleekXMPP#314]
Simple code:

``` python
import sleekxmpp
import logging

logging.basicConfig(level=logging.DEBUG, format='%(levelname)-8s %(message)s')

client = sleekxmpp.ClientXMPP("from@example.com", "secret")
def send(_):
    client.send_message(mto="to@example.com", mbody="Oh hi!", mtype="chat")
    client.disconnect(wait=True)
client.add_event_handler("session_start", send)
if client.connect(reattempt=False):
    client.process(block=True)
```

When running on PyPy (Python 3.2) causes an error:

``` python
$ pypy3 foo.py 
...
DEBUG     ==== TRANSITION disconnected -> connected
DEBUG    SEND (IMMED): <stream:stream to='im.etersoft.ru' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' xml:lang='en' version='1.0'>
ERROR    unknown event b'end'
Traceback (most recent call last):
  File "/home/mdevaev/.local/lib/python3.2/site-packages/sleekxmpp-1.3.1-py3.2.egg/sleekxmpp/xmlstream/xmlstream.py", line 1481, in _process
    if not self.__read_xml():
  File "/home/mdevaev/.local/lib/python3.2/site-packages/sleekxmpp-1.3.1-py3.2.egg/sleekxmpp/xmlstream/xmlstream.py", line 1523, in __read_xml
    for event, xml in ET.iterparse(self.filesocket, (b'end', b'start')):
  File "/opt/pypy3/lib-python/3/xml/etree/ElementTree.py", line 1242, in iterparse
    return _IterParseIterator(source, events, parser, close_source)
  File "/opt/pypy3/lib-python/3/xml/etree/ElementTree.py", line 1287, in __init__
    raise ValueError("unknown event %r" % event)
ValueError: unknown event b'end'
DEBUG    reconnecting...
DEBUG    Event triggered: session_end
DEBUG    SEND (IMMED): </stream:stream>
INFO     Waiting for </stream:stream> from server
DEBUG    Event triggered: disconnected
DEBUG     ==== TRANSITION connected -> disconnected
...
```

No messages. On pure python 3.2 working fine.

**Comment by bear** [comment]
I just ran this against my Prosody server and it works using Python v3.4, if it still fails let me know what server your trying against

... removed startup lines
DEBUG     ==== TRANSITION disconnected -> connected
DEBUG    Starting HANDLER THREAD
DEBUG    Loading event runner
DEBUG    SEND (IMMED): <stream:stream to='bear.im' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' xml:lang='en' version='1.0'>
DEBUG    RECV: <stream:stream xml:lang="en" version="1.0" id="a5ba2323-2cd8-4738-9605-63a91e761c65" from="bear.im">
DEBUG    RECV: <stream:features xmlns="http://etherx.jabber.org/streams"><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"><required /></starttls>/stream:features
DEBUG    SEND (IMMED): <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"><required /></starttls>
DEBUG    RECV: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls" />
DEBUG    Starting TLS
INFO     Negotiating TLS
INFO     Using SSL version: TLS 1.0
DEBUG    Event triggered: ssl_cert

... removed cert debug lines

DEBUG    SEND (IMMED): <stream:stream to='bear.im' xmlns:stream='http://etherx.jabber.org/streams' xmlns='jabber:client' xml:lang='en' version='1.0'>
DEBUG    RECV: <stream:stream xml:lang="en" version="1.0" id="09076311-dccf-4518-a053-b6b8f2ee4d39" from="bear.im">

**Comment by mdevaev** [comment]
It fails on **PyPy 3.2**, not on usual Python.

**Comment by bear** [comment]
I'll get v3.2 installed and try again - thanks

**Comment by mdevaev** [comment]
The server - jabber.ru
