### ISSUE TITLE
Unable to send image

### ISSUE THREAD

**Issue by pythonshiva** [fritzy/SleekXMPP#335]
I am trying to send image with sleekxmpp as given in the example "ibb_sender.py"(https://github.com/fritzy/SleekXMPP/tree/develop/examples/ibb_transfer). When i am executing like the following

python ibb_sender -d -j testuser2@domain.com -r testuser3@domain.com -p pass123 -f "crowd.png"
# I am getting the following error

ERROR    Error processing event handler: <bound method IBBSender.start of <__main__.IBBSender object at 0x0000000002C3FE48>>
Traceback (most recent call last):
  File "d:\Python27\lib\site-packages\sleekxmpp\xmlstream\xmlstream.py", line 1699, in _event_runner
    func(*args)
  File "send_file.py", line 69, in start
    stream = self['xep_0047'].open_stream(self.receiver)
  File "d:\Python27\lib\site-packages\sleekxmpp\plugins\xep_0047\ibb.py", line 143, in open_stream
    resp = iq.send(timeout=timeout)
  File "d:\Python27\lib\site-packages\sleekxmpp\stanza\iq.py", line 235, in send
    raise IqError(result)
IqError
ERROR    service-unavailable:
WARNING  You should catch IqError exceptions
DEBUG    Event triggered: presence
DEBUG    Event triggered: presence_available
DEBUG    Event triggered: presence
DEBUG    Event triggered: presence_available
DEBUG    Event triggered: presence
DEBUG    Event triggered: presence_available
DEBUG    Event triggered: got_online
DEBUG    Event triggered: changed_status
DEBUG    Event triggered: got_online
DEBUG    Event triggered: changed_status
DEBUG    Event triggered: changed_status

**Comment by elya5** [comment]
I just ran into the same issue. There is at least a problem that `open_stream()` with `use_messages=True` does not work and it could be fixed (in [this file](https://github.com/fritzy/SleekXMPP/blob/develop/sleekxmpp/plugins/xep_0047/ibb.py#L131)) with:

    if use_messages:
        iq['ibb_open']['stanza'] = 'message'
    else:
        iq['ibb_open']['stanza'] = 'iq'

But this is just something I noticed along the way and it does not solve the fact that sending a file does not work.

**Comment by elya5** [comment]
I am pretty sure this is not a bug. The `ERROR service-unavailable` rather suggests that the other side simply does not support IBB.
