### ISSUE TITLE
Python3 XEP-0084 error 

### ISSUE THREAD

**Issue by ricco386** [fritzy/SleekXMPP#353]
executing example file set_avatar.py in python3 fails with an exception:

```
python3 set_avatar.py -j *** -p *** -f avatar.png
ERROR    Error processing event handler: <bound method AvatarSetter.start of <__main__.AvatarSetter object at 0x7f7fbf97eeb8>>
Traceback (most recent call last):
  File "/home/ricco/Erigones/Ludolph/envs3/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1645, in _threaded_event_wrapper
    func(*args)
  File "set_avatar.py", line 71, in start
    avatar = avatar_file.read()
  File "/usr/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
ERROR    'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
Traceback (most recent call last):
  File "/home/ricco/Erigones/Ludolph/envs3/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1645, in _threaded_event_wrapper
    func(*args)
  File "set_avatar.py", line 71, in start
    avatar = avatar_file.read()
  File "/usr/lib/python3.4/codecs.py", line 313, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

Python 3.4.0
SleekXMPP 1.3.1 (and current master)

**Comment by ricco386** [comment]
Created pull request with bug fix: https://github.com/fritzy/SleekXMPP/pull/354
