### ISSUE TITLE
"Cannot seriazlize socket object" with Socks5 Bytestream

### ISSUE THREAD

**Issue by elya5** [fritzy/SleekXMPP#383]
I am trying to receive a file with a Socks5 Bytestream (XEP 65) but the following error occurs:

```
Exception in thread event_thread_0:
Traceback (most recent call last):
  File "/usr/lib64/python3.4/threading.py", line 921, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.4/threading.py", line 869, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/.local/lib/python3.4/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1680, in _event_runner
    orig = copy.copy(args[0])
  File "/usr/lib64/python3.4/copy.py", line 97, in copy
    rv = reductor(2)
  File "/usr/lib64/python3.4/socket.py", line 164, in __getstate__
    raise TypeError("Cannot serialize socket object")
TypeError: Cannot serialize socket object
```

The file was sent with Pidgin and I used the git version of SleekXMPP. I can also provide some demo code if it is necessary

**Comment by bear** [comment]
pinging @keith-gray-powereng so they are aware of the issue
