### ISSUE TITLE
ERROR    Error processing stream handler: Stream Features

### ISSUE THREAD

**Issue by x011** [fritzy/SleekXMPP#400]
I've a Simple Faceboook Echo Bot (based on the echobot example) that can connect and stay connected for a couple of seconds but then it gets disconnect  with this error:

ERROR    Error processing stream handler: Stream Features
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1675, in _event_runner
    handler.run(args[0])
  File "/usr/lib/python2.6/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/usr/lib/python2.6/site-packages/sleekxmpp/clientxmpp.py", line 280, in _handle_stream_features
    if handler(features) and restart:
  File "/usr/lib/python2.6/site-packages/sleekxmpp/features/feature_session/session.py", line 47, in _handle_start_session
    iq.send(now=True)
  File "/usr/lib/python2.6/site-packages/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
IqTimeout
ERROR    Error handling {jabber:client}features stanza
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1675, in _event_runner
    handler.run(args[0])
  File "/usr/lib/python2.6/site-packages/sleekxmpp/xmlstream/handler/callback.py", line 76, in run
    self._pointer(payload)
  File "/usr/lib/python2.6/site-packages/sleekxmpp/clientxmpp.py", line 280, in _handle_stream_features
    if handler(features) and restart:
  File "/usr/lib/python2.6/site-packages/sleekxmpp/features/feature_session/session.py", line 47, in _handle_start_session
    iq.send(now=True)
  File "/usr/lib/python2.6/site-packages/sleekxmpp/stanza/iq.py", line 233, in send
    raise IqTimeout(self)
IqTimeout

Do you have any idea what the problem is and how to fix ?
Thank you.

**Comment by cwaddell** [comment]
I'm having this same issue both with python2, and python3.

**Comment by waelbeso** [comment]
I think you need to review the server settings,

**Comment by fenchu** [comment]
I get similar error, My challenge is that we have a xmpp proxy, I can authenticate ok, but requesting resources fails, the proxy do not adhere to the standard. 
```
sleekxmpp.exceptions.IqTimeout: <iq id="27361723-b0d7-4f50-8760-8501ffc91b0e-1" type="set"><bind xmlns="urn:ietf:params:xml:ns:xmpp-bind" /></iq>
ERROR    Error handling {jabber:client}features stanza
Traceback (most recent call last):
  File "/home/mortenb/.pyenv/versions/xmpp/lib/python3.6/site-packages/sleekxmpp/xmlstream/xmlstream.py", line 1686, in _event_runner
    handler.run(args[0])
```
