### ISSUE TITLE
in develop branch xep_0199 Ping.sendPing = Ping.send_ping

### ISSUE THREAD

**Issue by shawnbutts** [fritzy/SleekXMPP#87]
In plugins/xep_0199/ping.py the last line is Ping.sendPing = Ping.send_ping

It seems to cause this error:

Unable to load plugin: xep_0199#012Traceback (most recent call last):#012  File "/usr/lib/python2.7/site-packages/sleekxmpp/basexmpp.py", line 167, in register_plugin#012    globals(), locals(), [plugin])#012  File "/usr/lib/python2.7/site-packages/sleekxmpp/plugins/xep_0199/**init**.py", line 10, in <module>#012    from sleekxmpp.plugins.xep_0199.ping import xep_0199#012  File "/usr/lib/python2.7/site-packages/sleekxmpp/plugins/xep_0199/ping.py", line 163, in <module>#012    Ping.sendPing = Ping.send_ping#012AttributeError: type object 'Ping' has no attribute 'send_ping'

**Comment by shawnbutts** [comment]
found the fix in the latest develop.  Sorry.
