### ISSUE TITLE
Threading issues when closing an app too fast

### ISSUE THREAD

**Issue by jleclanche** [fritzy/SleekXMPP#95]
If the app is closed too fast after login, I (rarely) get an exception:

Exception in thread send_thread (most likely raised during interpreter shutdown):
```pytb
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp/xmlstream/xmlstream.py", line 1073, in run_with_except_hook
<type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'excepthook'
```

**Comment by legastero** [comment]
Right, the issue is that modules are being unloaded from memory in arbitrary order, and so things like this happen when functions still try to reference them.

The only way I'm aware of to fix this is to keep local references to any modules a function uses, which is a bit impractical.

**Comment by fritzy** [comment]
Does this happen when you call disconnect and wait for the session_end event? I doubt it would.
