### ISSUE TITLE
UnboundLocalError when try connect to localhost and dnspython installed

### ISSUE THREAD

**Issue by UndeRus** [fritzy/SleekXMPP#99]
When I set JID located at localhost and dnspython is installed, sleekxmpp can't resolve server address and fall with UnboundLocalError.

Here is my tracback:

Traceback (most recent call last):
  File "zetsubo.py", line 77, in <module>
    bot.run()
  File "/home/illios/projects/zetsubo/jbot.py", line 175, in run
    if self.connect():
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp-1.0rc1-py2.7.egg/sleekxmpp/clientxmpp.py", line 141, in connect
    use_tls=use_tls, reattempt=reattempt)
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp-1.0rc1-py2.7.egg/sleekxmpp/xmlstream/xmlstream.py", line 333, in connect
    func=self._connect)
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp-1.0rc1-py2.7.egg/sleekxmpp/thirdparty/statemachine.py", line 68, in transition
    func=func, args=args, kwargs=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp-1.0rc1-py2.7.egg/sleekxmpp/thirdparty/statemachine.py", line 106, in transition_any
    return_val = func(_args,_*kwargs) if func is not None else True
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp-1.0rc1-py2.7.egg/sleekxmpp/xmlstream/xmlstream.py", line 343, in _connect
    self.address[1])
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp-1.0rc1-py2.7.egg/sleekxmpp/xmlstream/xmlstream.py", line 697, in pick_dns_answer
    self.dns_answers = self.get_dns_records(domain, port)
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp-1.0rc1-py2.7.egg/sleekxmpp/clientxmpp.py", line 163, in get_dns_records
    answers = super(ClientXMPP, self).get_dns_records(domain, port)
  File "/usr/local/lib/python2.7/dist-packages/sleekxmpp-1.0rc1-py2.7.egg/sleekxmpp/xmlstream/xmlstream.py", line 679, in get_dns_records
    answers = [((answer.address, port), 0, 0) for answer in answers]
UnboundLocalError: local variable 'answers' referenced before assignment

**Comment by legastero** [comment]
Yeah, RC1 has a few issues. This should be fixed in the develop branch.

**Comment by legastero** [comment]
This has been released in RC2
